#spring.application.name=EmployeeManagementSystem
#
#spring.datasource.url=jdbc:oracle:thin:@10.10.11.111:1521/FREEPDB1
#spring.datasource.username=SpringDB_Prod
#spring.datasource.password=******
#spring.jpa.hibernate.ddl-auto=update
#server.port=8080